[project]
name = "eabdl_microsam_cellpose3"
authors = ["bnorthan <bnorthan@gmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64"]
version = "0.1.0"

[system-requirements]
cuda = "12.0"

[dependencies]
python = "3.11.*"
micro_sam = "*"
cellpose = "<4"
monai = "*"

[pypi-dependencies]
tnia-python = { git = "https://github.com/True-North-Intelligent-Algorithms/tnia-python.git" }

# Use this to install from GitHub directly
napari-easy-augment-batch-dl = { git = "https://github.com/True-North-Intelligent-Algorithms/napari-easy-augment-batch-dl.git" }

# for specific commit
#napari-easy-augment-batch-dl = { 
#  git = "https://github.com/True-North-Intelligent-Algorithms/napari-easy-augment-batch-dl.git",
#  rev = "ebbdd2c314556fc736edb2660a130f4e75860861"
#    }

# Use this to install from local folder in editable mode
# napari-easy-augment-batch-dl = { path = "../..", editable = true }

[target.linux-64.dependencies]
pytorch-gpu = "*"

[target.win-64.dependencies]
pytorch-gpu = "*"

[target.osx-arm64.dependencies]
pytorch = "*"  # CPU-only PyTorch for macOS

[tasks]
startup = "python startup.py"